# -- Main Menu --
# 顶部主导航菜单

[[main]]
  name = "首页"
  url = "/"
  weight = 10

[[main]]
  name = "机场推荐"
  url = "/airports/"
  weight = 20

[[main]]
  name = "博客归档"
  url = "/posts/"
  weight = 30

[[main]]
  name = "工具使用"
  url = "/tools/"
  weight = 40

[[main]]
  name = "免责声明"
  url = "/disclaimer/"
  weight = 50

# -- Footer Menu --
# 底部页脚菜单

[[footer]]
  name = "首页"
  url = "/"
  weight = 10

[[footer]]
  name = "博客归档"
  url = "/posts/"
  weight = 20

[[footer]]
  name = "免责声明"
  url = "/disclaimer/"
  weight = 30
